export default [
  {
    id: 1,
    title: "The Thrill Is Gone",
    artist: "B.B. King",
    genre: "Blues",
    album: "Completely Well",
  },
  {
    id: 2,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    album: "Divide",
  },
  {
    id: 3,
    title: "Crossroads",
    artist: "Robert Johnson",
    genre: "Blues",
    album: "King of the Delta",
  },
  {
    id: 4,
    title: "Clair de Lune",
    artist: "Flight Facilities",
    genre: "Electronic",
    album: "Down to Earth",
  },
  {
    id: 5,
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Pop",
    album: "After Hours",
  },
  {
    id: 6,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    genre: "Rock",
    album: "Led Zeppelin IV",
  },
  {
    id: 7,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    album: "A Night at the Opera",
  },
  {
    id: 8,
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Pop",
    album: "Future Nostalgia",
  },
  {
    id: 9,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    genre: "Pop",
    album: "Fine Line",
  },
  {
    id: 10,
    title: "Bad Guy",
    artist: "Billie Eilish",
    genre: "Pop",
    album: "When We All Fall Asleep",
  },
  {
    id: 11,
    title: "Peaches",
    artist: "Justin Bieber",
    genre: "Pop",
    album: "Justice",
  },
  {
    id: 12,
    title: "So What",
    artist: "Miles Davis",
    genre: "Jazz",
    album: "Kind of Blue",
  },
  {
    id: 13,
    title: "Take Five",
    artist: "Dave Brubeck Quartet",
    genre: "Jazz",
    album: "Time Out",
  },
  {
    id: 14,
    title: "Stay",
    artist: "The Kid LAROI",
    genre: "Pop",
    album: "Single (Upcoming Album)",
  },
  {
    id: 15,
    title: "Save Your Tears",
    artist: "The Weeknd",
    genre: "Pop",
    album: "After Hours (Remixes)",
  },

  {
    id: 16,
    title: "Sweet Child o' Mine",
    artist: "Guns N' Roses",
    genre: "Rock",
    album: "Appetite for Destruction",
  },
  {
    id: 17,
    title: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    album: "Hotel California",
  },
  {
    id: 18,
    title: "Livin' on a Prayer",
    artist: "Bon Jovi",
    genre: "Rock",
    album: "Slippery When Wet",
  },
  {
    id: 19,
    title: "Sicko Mode",
    artist: "Travis Scott",
    genre: "Hip Hop",
    album: "Astroworld",
  },
  {
    id: 20,
    title: "Old Town Road",
    artist: "Lil Nas X",
    genre: "Hip Hop",
    album: "Single",
  },
  {
    id: 21,
    title: "God's Plan",
    artist: "Drake",
    genre: "Hip Hop",
    album: "Scorpion",
  },
  {
    id: 22,
    title: "StringMax",
    artist: "Drake",
    genre: "Electronic",
    album: "Scorpion",
  },
  {
    id: 23,
    title: "WolfStand",
    artist: "Drake",
    genre: "Classical",
    album: "Slippery",
  },
];
