export default [
  {
    id: 1,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    album: "Divide",
  },
  {
    id: 2,
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Pop",
    album: "After Hours",
  },
  {
    id: 3,
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Pop",
    album: "Future Nostalgia",
  },
  {
    id: 4,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    genre: "Pop",
    album: "Fine Line",
  },
  {
    id: 5,
    title: "Bad Guy",
    artist: "Billie Eilish",
    genre: "Pop",
    album: "When We All Fall Asleep",
  },
  {
    id: 6,
    title: "Peaches",
    artist: "Justin Bieber",
    genre: "Pop",
    album: "Justice",
  },
  {
    id: 7,
    title: "Stay",
    artist: "The Kid LAROI",
    genre: "Pop",
    album: "Single (Upcoming Album)",
  },
  {
    id: 8,
    title: "Save Your Tears",
    artist: "The Weeknd",
    genre: "Pop",
    album: "After Hours (Remixes)",
  },
  {
    id: 9,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    genre: "Rock",
    album: "Led Zeppelin IV",
  },
  {
    id: 10,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    album: "A Night at the Opera",
  },
  {
    id: 11,
    title: "Sweet Child o' Mine",
    artist: "Guns N' Roses",
    genre: "Rock",
    album: "Appetite for Destruction",
  },
  {
    id: 12,
    title: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    album: "Hotel California",
  },
  {
    id: 13,
    title: "Livin' on a Prayer",
    artist: "Bon Jovi",
    genre: "Rock",
    album: "Slippery When Wet",
  },
  {
    id: 14,
    title: "Sicko Mode",
    artist: "Travis Scott",
    genre: "Hip Hop",
    album: "Astroworld",
  },
  {
    id: 15,
    title: "Old Town Road",
    artist: " Lil Nas X",
    genre: "Hip Hop",
    album: "Single",
  },
  {
    id: 16,
    title: "God's Plan",
    artist: "Drake",
    genre: "Hip Hop",
    album: "Scorpion",
  },
];
